server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  output:
    ansi:
      enabled: always
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: CorsFilter
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service(/(?<segment>.+))?, /$\{segment}

        - id: user-service-login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service(/(?<segment>.+))?, /$\{segment}

        - id: user-service-join
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service(/(?<segment>.+))?, /$\{segment}

        - id: user-service-jwt
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service(/(?<segment>.+))?, /$\{segment}
            - name: JwtAuthorizationFilter

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/catalog-service(/(?<segment>.+))?, /$\{segment}

        - id: catalog-service-jwt
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/catalog-service(/(?<segment>.+))?, /$\{segment}
            - name: JwtAuthorizationFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service(/(?<segment>.+))?, /$\{segment}

        - id: order-service-jwt
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service(/(?<segment>.+))?, /$\{segment}
            - name: JwtAuthorizationFilter



token:
  exp: 864000000
  secret: metacoding
